# Welcome to Cloud Functions for Firebase for Python!
# To get started, simply uncomment the below code or create your own.
# Deploy with `firebase deploy`

# The Cloud Functions for Firebase SDK to create Cloud Functions and set up triggers.
from firebase_functions import firestore_fn, https_fn

import firebase_functions

# The Firebase Admin SDK to access Cloud Firestore.
from firebase_admin import initialize_app, firestore
import google.cloud.firestore

app = initialize_app()


@https_fn.on_request()
def addmessage(req: https_fn.Request) -> https_fn.Response:
    """Take the text parameter passed to this HTTP endpoint and insert it into
    a new document in the messages collection."""
    # Grab the text parameter.
    original = req.args.get("text")
    if original is None:
        return https_fn.Response("No text parameters provided", status=400)

    firestore_client: google.cloud.firestore.Client = firestore.client()

    # Push the new message into Cloud Firestore using the Firebase Admin SDK.
    _, doc_ref = firestore_client.collection("messages").add({"original": original})

    # Send back a message that we've successfully written the message
    return https_fn.Response(f"Message with ID {doc_ref.id} added.")

@https_fn.on_request()
def createpost(req: https_fn.Request) -> https_fn.Response:
    """Takes in a topic and populates firebase with a new post on 
    that topic generated by a call to an LLM API"""
    topic = req.args.get("topic")
    if topic is None:
        return https_fn.Response("No topic provided for post generation")
    
    firestore_client: google.cloud.firestore.Client = firestore.client()

    title = "Sam Altman: The YC Founder who could."
    summary = "Some summary about teh wonders of AI and human ingenuity"
    content = """
    # Sam Altman: The YC Founder who could

    This is an interesting topic!

    ## Here is a subheader

    here is some more interesting information
    """
    _, doc_ref = firestore_client.collection("staging_posts").add({
        "title": title,
        "summary": summary,
        "content": content
    })

    return https_fn.Response(f"Created a new post ({doc_ref.id}). [{title}]")

@firestore_fn.on_document_created(document="messages/{pushId}")
def makeuppercase(event: firestore_fn.Event[firestore_fn.DocumentSnapshot | None]) -> None:
    """Listens for new documents to be added to /messages. If the document has
    an "original" field, creates an "uppercase" field containg the contents of
    "original" in upper case."""

    # Get the value of "original" if it exists.
    if event.data is None:
        return
    try:
        original = event.data.get("original")
    except KeyError:
        # No "original" field, so do nothing.
        return

    # Set the "uppercase" field.
    print(f"Uppercasing {event.params['pushId']}: {original}")
    upper = original.upper()
    event.data.reference.update({"uppercase": upper})